apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: myweb-rs
spec:
   replicas: 3
   selector:
      matchLabels: 
          env: production
               # matchExpression: 
             
   template:
      metadata:
           name: myweb-pod
           labels:
             env: production
      spec:
        containers:
              - name: mywebcon
                image: vimal13/apache-webserver-php
